In [1]:
import numpy as np

In [2]:
myarr=np.array([3,6,32,7],np.int64)

In [3]:
myarr

array([ 3,  6, 32,  7], dtype=int64)

In [4]:
myarr.shape

(4,)

In [5]:
myarr.dtype

dtype('int64')

**#ways to implement**

In [6]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
listarray.dtype

dtype('int32')

In [11]:
zeros=np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
l=np.linespace(1,5,12)

AttributeError: module 'numpy' has no attribute 'linespace'

In [14]:
emp=np.empty((4,6))

In [15]:
ide=np.identity(45)

In [16]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [17]:
arr=np.arrange(99)

AttributeError: module 'numpy' has no attribute 'arrange'

In [18]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [19]:
ar=np.array(x)

In [20]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [21]:
ar.sum()

29

In [22]:
ar.sum(axis=0)

array([12,  8,  9])

In [23]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [24]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [25]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [26]:
ar.size

9

In [27]:
ar.nbytes

36

In [28]:
one=np.array([1,3,4,634,2])

In [29]:
one.argmax()

3

In [30]:
one.argmin()

0

In [31]:
one.argmax()

3

In [32]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [33]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [34]:
ar.reshape(9,)

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [35]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [36]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [37]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [38]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [39]:
ar.sum()

29

In [40]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [41]:
np.count_nonzero(ar)

8

In [42]:
import sys

In [43]:
py_ar=[0,4,55,2]

In [44]:
np_ar=np.array(py_ar)

In [45]:
sys.getsizeof(1)*len(py_ar)

112

In [46]:
np_ar.itemsize*np_ar.size

16